/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output;

import Data.Movie;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JFrame;
import movielens.Repository;

/**
 *
 * @author fes77
 */
public class MovieListPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form MovieListPanel
     */
    List<MovieCard> movies;
    ExecutorService executor;
    public MovieListPanel1() {
        initComponents();
        removeAll();
//        setMinimumSize(new Dimension(100, 235));
        GridLayout layout = (GridLayout) getLayout();
        layout.setColumns(Math.max(getWidth() / 230, 1));
        layout.setRows(Math.max(getHeight() / 250, 1));
        movies = new LinkedList();
        
        executor = Executors.newFixedThreadPool(5);
        
        updateMovies();
        
    }

    private void updateMovies() {
        int nCols = Math.max(getWidth() / 230, 1);
        int nRows = Math.max(getHeight() / 250, 1);
        int totalSize = nCols * nRows;
        int currentSize = getComponentCount();
        GridLayout layout = (GridLayout) getLayout();
        System.out.println("[B]Total ( " + nCols + ", " + nRows + ") " + totalSize);
        System.out.println("[B]Current " + currentSize);
        if(currentSize == totalSize)
        {
            System.out.println("Return");
            return;
        }
        
        List<Movie> addingMovies = Repository.findTopRatedMovies(movies.size(), totalSize - movies.size());
        for (int i = 0; i < addingMovies.size(); i++) {
            MovieCard card = new MovieCard(addingMovies.get(i));
            movies.add(card);
            System.out.println("Adding into list");
        }

        
        for (int i = currentSize; i < totalSize; i++) {
            add(movies.get(i));
        }
        
        for(int i = totalSize; i < currentSize; i++)
        {
            remove(movies.get(i));
        }
        
        System.out.println("[R]Current " + getComponentCount() + "\n\n\n");

        layout.setColumns(Math.max(nCols, 1));
        layout.setRows(Math.max(nRows, 1));
        validate();
        repaint();
    }

    public static void main(String[] args) {
        Repository.connect(Repository.Driver.MySQL ,"movie-lens.cpzst9uo9qun.ap-northeast-1.rds.amazonaws.com", 3306, "mydb" , "root", "rsTTMA2sHyUL");
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(800, 300));
        MovieListPanel1 movieListPanel = new MovieListPanel1();
//            cell.setBackground(new Color(34, 34, 34));
        frame.setBackground(new Color(34, 34, 34));
        frame.add(movieListPanel);
        frame.setVisible(true);
//        Scanner sk = new Scanner(System.in);
//        while(true)
//        {
//            if(sk.nextInt() == 1)
//                frame.repaint();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieCard1 = new Output.MovieCard();
        movieCard3 = new Output.MovieCard();
        movieCard2 = new Output.MovieCard();
        movieCard4 = new Output.MovieCard();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.GridLayout(2, 2));
        add(movieCard1);
        add(movieCard3);
        add(movieCard2);
        add(movieCard4);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
//        System.out.println(getWidth());
//        System.out.println(getHeight());
//        GridLayout layout = (GridLayout)getLayout();
//        layout.setColumns(Math.max(getWidth() / 200, 1));
//        layout.setRows(Math.max(getHeight() / 400, 1));
        updateMovies();
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Output.MovieCard movieCard1;
    private Output.MovieCard movieCard2;
    private Output.MovieCard movieCard3;
    private Output.MovieCard movieCard4;
    // End of variables declaration//GEN-END:variables
}
