/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author fes77
 */
public class MovieListPanel extends javax.swing.JPanel {

    /**
     * Creates new form MovieListPanel
     */
    List<MovieCard> movies;

    public MovieListPanel() {
        initComponents();
        removeAll();
//        setMinimumSize(new Dimension(100, 235));
        GridLayout layout = (GridLayout) getLayout();
        layout.setColumns(Math.max(getWidth() / 200, 1));
        layout.setRows(Math.max(getHeight() / 400, 1));
        movies = new LinkedList();
        updateMovies();
        
    }

    private void updateMovies() {
        int nCols = Math.max(getWidth() / 200, 1);
        int nRows = Math.max(getHeight() / 250, 1);
        int totalSize = nCols * nRows;
        int currentSize = getComponentCount();
        GridLayout layout = (GridLayout) getLayout();
        System.out.println("[B]Total ( " + nCols + ", " + nRows + ") " + totalSize);
        System.out.println("[B]Current " + currentSize);
        if(currentSize == totalSize)
        {
            System.out.println("Return");
            return;
        }
        else if (currentSize < totalSize) {
            
            for (int i = 0; i <= totalSize - movies.size(); i++) {
                MovieCard card = new MovieCard();
                movies.add(card);
                System.out.println("Adding into list");
            }

            for (int i = 0; i < totalSize - currentSize; i++) {
                add(movies.get(movies.size() - 1 - i));
            }
        } else {
            
            int n = movies.size();
//            System.out.println("Diff " + (n - totalSize));
//            System.out.println("Total " + totalSize);
//            for (int i = 0; i < n - totalSize; i++) {
//                MovieCard card = movies.remove(movies.size() - 1);
//                System.out.println("Removing from list");
//            }

            for (int i = 0; i < getComponentCount() - totalSize; i++) {
                remove(getComponentCount() - 1);
            }
//            System.out.println(movies.size());
        }
        
        System.out.println("[R]Current " + getComponentCount() + "\n\n\n");

        layout.setColumns(Math.max(nCols, 1));
        layout.setRows(Math.max(nRows, 1));
        validate();
        repaint();
    }

    public static void main(String[] args) {

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(800, 300));
        MovieListPanel movieListPanel = new MovieListPanel();
//            cell.setBackground(new Color(34, 34, 34));
        frame.setBackground(new Color(34, 34, 34));
        frame.add(movieListPanel);
        frame.setVisible(true);
//        Scanner sk = new Scanner(System.in);
//        while(true)
//        {
//            if(sk.nextInt() == 1)
//                frame.repaint();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieCard1 = new Output.MovieCard();
        movieCard3 = new Output.MovieCard();
        movieCard2 = new Output.MovieCard();
        movieCard4 = new Output.MovieCard();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.GridLayout(2, 2));
        add(movieCard1);
        add(movieCard3);
        add(movieCard2);
        add(movieCard4);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
//        System.out.println(getWidth());
//        System.out.println(getHeight());
//        GridLayout layout = (GridLayout)getLayout();
//        layout.setColumns(Math.max(getWidth() / 200, 1));
//        layout.setRows(Math.max(getHeight() / 400, 1));
        updateMovies();
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Output.MovieCard movieCard1;
    private Output.MovieCard movieCard2;
    private Output.MovieCard movieCard3;
    private Output.MovieCard movieCard4;
    // End of variables declaration//GEN-END:variables
}
