/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output.Old;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JFrame;

/**
 *
 * @author fes77
 */
public class MovieScrollPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form MovieScrollPanel
     */
    public MovieScrollPanel1() {
        initComponents();
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(800, 300));
        MovieScrollPanel1 movieListPanel = new MovieScrollPanel1();
//            cell.setBackground(new Color(34, 34, 34));
        frame.setBackground(new Color(34, 34, 34));
        frame.add(movieListPanel);
        frame.setVisible(true);
//        Scanner sk = new Scanner(System.in);
//        while(true)
//        {
//            if(sk.nextInt() == 1)
//                frame.repaint();
//        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        
        setPreferredSize(new Dimension(movieListPanel.getCols() * 230, movieListPanel.getRows() * 300));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieListScrollPane = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        movieListPanel = new Output.GridView.MovieGridPanel(20, 5);
        jButton2 = new javax.swing.JButton();

        movieListScrollPane.getVerticalScrollBar().setUnitIncrement(25);

        containerPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                containerPanelComponentAdded(evt);
            }
        });

        movieListPanel.setPreferredSize(new java.awt.Dimension(500, 1000));

        jButton2.setText("jButton2");

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap(337, Short.MAX_VALUE))
            .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(movieListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 729, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(jButton2))
            .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerPanelLayout.createSequentialGroup()
                    .addComponent(movieListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addGap(25, 25, 25)))
        );

        movieListScrollPane.setViewportView(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movieListScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movieListScrollPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void containerPanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_containerPanelComponentAdded
        // TODO add your handling code here:
        setPreferredSize(new Dimension(movieListPanel.getCols() * 230, movieListPanel.getRows() * 300));
        System.out.println("aaa");
    }//GEN-LAST:event_containerPanelComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton jButton2;
    private Output.GridView.MovieGridPanel movieListPanel;
    private javax.swing.JScrollPane movieListScrollPane;
    // End of variables declaration//GEN-END:variables
}
