/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output.StackView;

import Output.DetailedView.MovieDetailPanel;
import Output.ListView.MovieScrollPanel;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.Scanner;
import java.util.Stack;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author fes77
 */
public class MovieStackedPanel extends javax.swing.JPanel {
    public static MovieStackedPanel STACK_PANEL = null; 
    /**
     * Creates new form MovieStackedPanel
     */
    CardLayout layout;
    Stack<JPanel> movieStack;
    
    public MovieStackedPanel() {
        initComponents();
        add(new MovieScrollPanel());
        layout = (CardLayout)getLayout();
        movieStack = new Stack<>();
        STACK_PANEL = this;
    }
    
    public void addMovie(int movieId)
    {
        MovieDetailPanel panel = new MovieDetailPanel(movieId);
        movieStack.push(panel);
//        layout.addLayoutComponent(panel, panel.toString());
////        layout.show(this, panel.toString());
//        layout.next(this);
        add(panel);
        layout.next(this);
    }
    
    public void previous()
    {
        if(movieStack.size() <= 1)
        {
            System.out.println("Cannot pop last element ");
            return;
        }
        JPanel tagFirst = movieStack.pop();
        layout.removeLayoutComponent(tagFirst);
        
    }
    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(1000, 800));
        MovieStackedPanel stackPanel = new MovieStackedPanel();
//            cell.setBackground(new Color(34, 34, 34));
//        frame.setBackground(new Color(34, 34, 34));
        frame.add(stackPanel);
        frame.setVisible(true);
        Scanner sk = new Scanner(System.in);
        while(true)
        {
            int i;
            if((i = sk.nextInt()) != 0)
            {
                stackPanel.add(new MovieDetailPanel(i));
                ((CardLayout)stackPanel.getLayout()).next(stackPanel);
                System.out.println(stackPanel.getComponentCount());
            }
            else{
//                ((CardLayout)stackPanel.getLayout()).previous(stackPanel);
                stackPanel.remove(stackPanel.getComponentCount() - 1);
                System.out.println(stackPanel.getComponentCount());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
