/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Icon;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JFrame;


/**
 *
 * @author fes77
 */
public class BaseIcon extends javax.swing.JPanel {
    
    protected Color color;
    protected Color bgColor;

    Thread thread;
    
    protected float marginPercentage;
//    protected float paddingPercentage;
    protected float lineThicknessPercentage;

    
    public static float PADDING_PERCENTAGE = 0.5f;
   
    
    

    public final static Color INITIAL_BG_COLOR = new Color(8,28,34);

    protected final static float INITIAL_LINE_THICKNESS_PERCENTAGE = .065f;
    protected final static float INITIAL_MARGINE_PERCENTAGE = .01f;
//    protected final static float INITIAL_PADDING_PERCENTAGE = .08f;
   
    
    /**
     * Creates new form BaseIcon
     */
    public BaseIcon() {
        initComponents();
        bgColor = INITIAL_BG_COLOR;
        
        marginPercentage = INITIAL_MARGINE_PERCENTAGE;
//        paddingPercentage = INITIAL_PADDING_PERCENTAGE;
        lineThicknessPercentage = INITIAL_LINE_THICKNESS_PERCENTAGE;
        color = Color.RED;
        
        thread = new Thread();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        Graphics2D g2d = (Graphics2D)g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        int height = getHeight();
        int width = getWidth();
        int length = height < width ? height : width;
        int margin = (int)(length * marginPercentage);
//        int padding = (int)(length * lineThicknessPercentage);
        int thickness = (int)(length * lineThicknessPercentage);
        
        int bgSize = length - 2 *  margin;
        int outerSize = length - 2 * (thickness + margin);
        
        int bgStartX = width / 2 - length / 2 + margin;
        int bgStartY = height / 2 - length / 2 + margin;
        int outerStartX = width / 2 - length / 2 + thickness + margin;
        int outerStartY = height / 2 - length / 2 + thickness + margin;
        
        g2d.setColor(bgColor);
        g2d.fillOval(bgStartX, bgStartY, bgSize, bgSize);
//        g2d.setColor(Color.BLACK);
//        g2d.fillOval(outerStartX, outerStartY, outerSize, outerSize);
        
        BasicStroke wideStroke = new BasicStroke(thickness, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND);
        g2d.setStroke(wideStroke);
        g2d.setColor(color);
        
        

    }

//    public abstract void clickAction(java.awt.event.MouseEvent e);
    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(1000, 800));
        BaseIcon movieListPanel = new BaseIcon();

        frame.add(movieListPanel);
        frame.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
