/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Icon.Demo;

import Icon.CrossIcon;
import Icon.FavoriteIcon;
import Icon.LinkIcon;
import Icon.PlayIcon;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author fes77
 */
public class IconDisplay extends javax.swing.JPanel {

    /**
     * Creates new form IconDisplay
     */
    public IconDisplay() {
        initComponents();
        add(new PlayIcon());
        add(new FavoriteIcon());
        add(new LinkIcon("https://www.google.com/search?q=github+read+me+%E6%9B%B8%E3%81%8D%E6%96%B9+docs&rlz=1C1ONGR_enUS993US993&hl=ja&biw=1707&bih=849&ei=Pb2BYoy3BpCK0gSx0pS4DA&ved=0ahUKEwjMybbOguP3AhUQhZQKHTEpBccQ4dUDCA4&uact=5&oq=github+read+me+%E6%9B%B8%E3%81%8D%E6%96%B9+docs&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsAM6BQgAEKIEOgQIIRAVSgQIQRgASgQIRhgAUE1Y7AtgrA5oAXABeACAAWiIAbEDkgEDNC4xmAEAoAEByAEKwAEB&sclient=gws-wiz"));
        add(new CrossIcon());
        
    }
    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(1000, 800));
        IconDisplay movieListPanel = new IconDisplay();

        frame.add(movieListPanel);
        frame.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
