/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Icon.Demo;

import Icon.RatingCircle;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author fes77
 */
public class RatingCircleDisplay extends javax.swing.JPanel {

    /**
     * Creates new form RatingCircleDisplay
     */
    public RatingCircleDisplay() {
        initComponents();
        add(new RatingCircle(0));
        add(new RatingCircle(1));
        add(new RatingCircle(2));
        add(new RatingCircle(3));
        add(new RatingCircle(4));
        add(new RatingCircle(5));
        add(new RatingCircle(6));
        add(new RatingCircle(7));
        add(new RatingCircle(8));
        add(new RatingCircle(9));
        add(new RatingCircle(10));

    }

    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(1000, 800));
        RatingCircleDisplay movieListPanel = new RatingCircleDisplay();

        frame.add(movieListPanel);
        frame.setVisible(true);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 4));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
