/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output.ListView;

import Data.Movie;

/**
 *
 * @author fes77
 */
public class MovieTopicListPanel extends javax.swing.JPanel {

    /**
     * Creates new form MovieListPanel
     */
    
    
    
    public MovieTopicListPanel() {
        initComponents();
//        relatedMoviesScrollPanel.scrollRectToVisible(focused);

    }
    
    public MovieTopicListPanel(Movie m) {
        initComponents();
        
//        DefaultListModel<MovieCard> model = new DefaultListModel();
        
//        relatedMoviesScrollPanel.scrollRectToVisible(focused);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        crossIcon2 = new Icon.CrossIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        controlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        relatedMoviesScrollPanel = new javax.swing.JScrollPane();
        relatedMoviesPanel = new javax.swing.JPanel();
        crossIcon1 = new Icon.CrossIcon();
        crossIcon3 = new Icon.CrossIcon();
        crossIcon4 = new Icon.CrossIcon();
        crossIcon5 = new Icon.CrossIcon();
        crossIcon6 = new Icon.CrossIcon();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout crossIcon2Layout = new javax.swing.GroupLayout(crossIcon2);
        crossIcon2.setLayout(crossIcon2Layout);
        crossIcon2Layout.setHorizontalGroup(
            crossIcon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        crossIcon2Layout.setVerticalGroup(
            crossIcon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Topic");

        javax.swing.GroupLayout controlePanelLayout = new javax.swing.GroupLayout(controlePanel);
        controlePanel.setLayout(controlePanelLayout);
        controlePanelLayout.setHorizontalGroup(
            controlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlePanelLayout.setVerticalGroup(
            controlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        relatedMoviesPanel.setLayout(new javax.swing.BoxLayout(relatedMoviesPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout crossIcon1Layout = new javax.swing.GroupLayout(crossIcon1);
        crossIcon1.setLayout(crossIcon1Layout);
        crossIcon1Layout.setHorizontalGroup(
            crossIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        crossIcon1Layout.setVerticalGroup(
            crossIcon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        relatedMoviesPanel.add(crossIcon1);

        javax.swing.GroupLayout crossIcon3Layout = new javax.swing.GroupLayout(crossIcon3);
        crossIcon3.setLayout(crossIcon3Layout);
        crossIcon3Layout.setHorizontalGroup(
            crossIcon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        crossIcon3Layout.setVerticalGroup(
            crossIcon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        relatedMoviesPanel.add(crossIcon3);

        javax.swing.GroupLayout crossIcon4Layout = new javax.swing.GroupLayout(crossIcon4);
        crossIcon4.setLayout(crossIcon4Layout);
        crossIcon4Layout.setHorizontalGroup(
            crossIcon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        crossIcon4Layout.setVerticalGroup(
            crossIcon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        relatedMoviesPanel.add(crossIcon4);

        javax.swing.GroupLayout crossIcon5Layout = new javax.swing.GroupLayout(crossIcon5);
        crossIcon5.setLayout(crossIcon5Layout);
        crossIcon5Layout.setHorizontalGroup(
            crossIcon5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        crossIcon5Layout.setVerticalGroup(
            crossIcon5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        relatedMoviesPanel.add(crossIcon5);

        javax.swing.GroupLayout crossIcon6Layout = new javax.swing.GroupLayout(crossIcon6);
        crossIcon6.setLayout(crossIcon6Layout);
        crossIcon6Layout.setHorizontalGroup(
            crossIcon6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        crossIcon6Layout.setVerticalGroup(
            crossIcon6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        relatedMoviesPanel.add(crossIcon6);

        relatedMoviesScrollPanel.setViewportView(relatedMoviesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(relatedMoviesScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relatedMoviesScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlePanel;
    private Icon.CrossIcon crossIcon1;
    private Icon.CrossIcon crossIcon2;
    private Icon.CrossIcon crossIcon3;
    private Icon.CrossIcon crossIcon4;
    private Icon.CrossIcon crossIcon5;
    private Icon.CrossIcon crossIcon6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel relatedMoviesPanel;
    private javax.swing.JScrollPane relatedMoviesScrollPanel;
    // End of variables declaration//GEN-END:variables
}
