/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output.ListView;

import Data.Genre;
import Data.Movie;
import Output.ScrollView.Scroll;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author fes77
 */
public class MovieTopicListPanel extends javax.swing.JPanel {

    /**
     * Creates new form MovieListPanel
     */
    
    
    Movie movie;
    Genre genre;
    String tag;
    Scroll type;
    public MovieTopicListPanel() {
        
//        relatedMoviesScrollPanel.scrollRectToVisible(focused);

        movie = new Movie(1, "Toy Story");
        type = Scroll.LINEAR;
        initComponents();
        prepareTopic();
    }
    
    // Related video to movie
    public MovieTopicListPanel(Scroll type, Movie m) {
        this.type = type;
        movie = m;
        initComponents();
        prepareTopic();
    }
    
    public MovieTopicListPanel(Scroll type, Genre g) {
        this.type = type;
        genre = g;
        initComponents();
        prepareTopic();
    }
    
    public MovieTopicListPanel(Scroll type, String tag) {
        this.type = type;
        this.tag = tag;
        initComponents();
        prepareTopic();
    }
    
    public void prepareTopic()
    {
        if(movie != null)
            topicLabel.setText("Similar movies to " + movie.getTitle());
        else if(genre != null)
            topicLabel.setText("Genre: " + genre);
        else if(tag != null)
            topicLabel.setText("Tag: " + tag);
        else
            topicLabel.setText("Top rated movies");
        
    }
    
    
    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(800, 600));
        MovieTopicListPanel movieListPanel = new MovieTopicListPanel();
//            cell.setBackground(new Color(34, 34, 34));
        frame.setBackground(new Color(34, 34, 34));
        frame.add(movieListPanel);
        frame.setVisible(true);
//        Scanner sk = new Scanner(System.in);
//        while(true)
//        {
//            if(sk.nextInt() == 1)
//                frame.repaint();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        crossIcon2 = new Icon.CrossIcon();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        controlePanel = new javax.swing.JPanel();
        topicLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        movieScrollPanel1 = new Output.ScrollView.MovieScrollPanel(
            5, 4, type, (int start, int size)->{
                if(movie != null)
                {
                    return SearchMovies.genreMostMatch(movie.getId(), start, size);
                }
                else if(genre != null)
                {
                    return SearchMovies.searchByGenre(genre, start, size);
                }
                else if(tag != null)
                {
                    return SearchMovies.searchByTag(tag, start, size);
                }
                return SearchMovies.topRated(start, size);
            });

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

            javax.swing.GroupLayout crossIcon2Layout = new javax.swing.GroupLayout(crossIcon2);
            crossIcon2.setLayout(crossIcon2Layout);
            crossIcon2Layout.setHorizontalGroup(
                crossIcon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 100, Short.MAX_VALUE)
            );
            crossIcon2Layout.setVerticalGroup(
                crossIcon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 100, Short.MAX_VALUE)
            );

            setBackground(new java.awt.Color(51, 51, 51));

            controlePanel.setBackground(new java.awt.Color(51, 51, 51));

            topicLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
            topicLabel.setForeground(new java.awt.Color(255, 255, 255));
            topicLabel.setText("Topic");

            jLabel2.setBackground(new java.awt.Color(51, 51, 51));
            jLabel2.setForeground(new java.awt.Color(51, 153, 255));
            jLabel2.setText("More movies");

            javax.swing.GroupLayout controlePanelLayout = new javax.swing.GroupLayout(controlePanel);
            controlePanel.setLayout(controlePanelLayout);
            controlePanelLayout.setHorizontalGroup(
                controlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(topicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addContainerGap())
            );
            controlePanelLayout.setVerticalGroup(
                controlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(topicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlePanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addContainerGap())
            );

            movieScrollPanel1.setBackground(new java.awt.Color(51, 51, 51));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(movieScrollPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(controlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(controlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(movieScrollPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
            );
        }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlePanel;
    private Icon.CrossIcon crossIcon2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private Output.ScrollView.MovieScrollPanel movieScrollPanel1;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables
}
