/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Output.ListView;

import Data.Movie;
import Output.ListView.GridView.MovieGridPanel;
import Output.MovieCard;
import Output.MovieCardProducer;
import Repository.Repository;
import Repository.SearchMovies;
import java.awt.Color;
import java.awt.Dimension;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JFrame;

/**
 *
 * @author fes77
 */
public abstract class MovieListView  extends javax.swing.JPanel{

    /**
     * Creates new form MovieGridPanel
     */
    List<MovieCard> movies;
    ExecutorService executor;
    int unit;
    int size;
    int nCols;
    int nRows;
    SearchMovies searchAction;
    
    boolean debug = false;
    
    public MovieListView()
    {
        initComponents();
        removeAll();
        if(Repository.isConnected() == false)
            Repository.connect(Repository.Driver.MySQL ,"movie-lens.cpzst9uo9qun.ap-northeast-1.rds.amazonaws.com", 3306, "mydb" , "root", "rsTTMA2sHyUL");
        
        debug = true;
        for(int i = 0; i < 20; i++)
        {
            add(new MovieCard(new Movie(0, "Sample Movie")));
        }
        
        unit = 20;
        validate();
        repaint();
    }
    
    public MovieListView(int size, int threadSize) {
        this(size, threadSize, (int start, int unitSize)->{
            return SearchMovies.topRated(start, size);
        });
    }
    
    public MovieListView(int size, int threadSize, SearchMovies sm) {
        initComponents();
        removeAll();
        
        if(Repository.isConnected() == false)
            Repository.connect(Repository.Driver.MySQL ,"movie-lens.cpzst9uo9qun.ap-northeast-1.rds.amazonaws.com", 3306, "mydb" , "root", "rsTTMA2sHyUL");
        
        movies = new LinkedList();
        executor = Executors.newFixedThreadPool(threadSize);
        this.unit = size;
        searchAction = sm;
        loadMovieCards(sm);
        validate();
        repaint();
    }
    
    public boolean isIdle()
    {
        return size == movies.size();
    }
    
    public void clearList(){
        removeAll();
        movies.clear();
        
    }
    public void loadMovieCards()
    {
        if(searchAction != null)
        {
            loadMovieCards(searchAction);
            return;
        }
        
        // TODO May need to rtemove this latyer
        setPreferredSize(null);
        int listSize = movies.size();
        List<Integer> addingMovies = Repository.findTopRatedMovieIds(size, unit);
        size += unit;
        
        
        
        for (int i = 0; i < addingMovies.size(); i++) {

            executor.execute(new MovieCardProducer(addingMovies.get(i), movies, this, true));
            System.out.println("Adding[" + i +  "] into list");
        }
    }
    
    public void loadMovieCards(SearchMovies sm) {
        searchAction = sm;
        int listSize = movies.size();
        List<Integer> addingMovies = sm.search(size, unit);
//        List<Integer> addingMovies = Repository.findTopRatedMovieIds(size, unit);
        size += unit;
        
        for (int i = 0; i < addingMovies.size(); i++) {

            executor.execute(new MovieCardProducer(addingMovies.get(i), movies, this, true));
            System.out.println("Adding[" + i +  "] into list");
        }
    }
    
    public void updateMovies() {
        // This is very important code to fix the issue where new loaded movies do not show on screen when screen is scrolled to the end.
        setPreferredSize(new Dimension(size * 230, 400));

        validate();
        repaint();
    }
    
    protected abstract void initComponents();
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(800, 300));
        MovieGridPanel movieListPanel = new MovieGridPanel(10, 5, (int start, int size)->{
            return Repository.findTopRatedMovieIds(start, size);
        });
        frame.setBackground(new Color(34, 34, 34));
        frame.add(movieListPanel);
        frame.setVisible(true);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
}
