/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output.ListView;

/**
 *
 * @author fes77
 */
import java.awt.*;
import javax.swing.*;

public class Page2 extends JFrame {
  public static void main(String [] args) {
    new Page2().setVisible(true);
  }
  
  Page2() {
    super("タイトル");
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    
    JPanel panel = new JPanel(null) { // constructorにLayoutManagerを指定できます。
      {  // 匿名クラスの初期化ブロックに書くとメソッドの操作対象を省略できる
        // 親(JViewport)はレイアウトマネージャーを持っているので推奨サイズ制約を設定しておく必要がある。
        // 逆にsetBoundsは意味がない。他も同様の考え方でどちらかを選択。
        setPreferredSize(new Dimension(100, 3000));
      }
    };
    JButton button = new JButton("ボタン") {
      {
        // 親のレイアウトマネージャーが無効なので自前でサイズを設定
        setBounds(5, 5, 100, 100);
      }
    };
    panel.add(button);
    
    JScrollPane scrollPane = new JScrollPane(panel) {
      {
        // 親はレイアウトマネージャーを持っているのでサイズ制約を設定
        setPreferredSize(new Dimension(510, 400));
      }
    };
    
    add(scrollPane, BorderLayout.CENTER); // こう書けばcontentPaneへのaddと解釈してくれる
    // Scrollpaneの下にもう一つ何か置いておきましょう。
    add(new JLabel("JFrameさん私も表示してください"), BorderLayout.SOUTH);
    
    // 全部自前でレイアウトしないかぎりpackは必須。
    // これが書かれてないswingアプリは異端に見えます :-P
    pack();
  }
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieSingleListPanel = new Output.ListView.MovieSingleListPanel(4, 4);
        horizontalScrollBar = new javax.swing.JScrollBar();

        horizontalScrollBar.setOrientation(javax.swing.JScrollBar.HORIZONTAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(horizontalScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(movieSingleListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 4606, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(movieSingleListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(horizontalScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar horizontalScrollBar;
    private Output.ListView.MovieSingleListPanel movieSingleListPanel;
    // End of variables declaration//GEN-END:variables
}
