/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output.ListView.LinearView;

import Output.ListView.MovieListView;
import Repository.Repository;
import Repository.SearchMovies;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author fes77
 */
public class MovieLinearPanel extends MovieListView {

    /**
     * Creates new form MovieSingleListPanel
     */
    public MovieLinearPanel() {
        super();
        
    }

    public MovieLinearPanel(int size, int threadSize) {
        super(size, threadSize);
    }

    public MovieLinearPanel(int size, int threadSize, SearchMovies sm) {
        super(size, threadSize, sm);
    }

    
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(800, 300));
        MovieLinearPanel movieListPanel = new MovieLinearPanel(10, 5, (int start, int size)->{
            return Repository.findTopRatedMovieIds(start, size);
        });
        
        frame.setBackground(new Color(34, 34, 34));
        frame.add(movieListPanel);
        frame.setVisible(true);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    protected void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
