/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Output.DetailedView;

import java.awt.Dimension;
import java.util.Scanner;
import javax.swing.JFrame;
import org.jdesktop.jdic.browser.WebBrowser;

/**
 *
 * @author fes77
 */
public class BrowserPanel extends javax.swing.JPanel {

    /**
     * Creates new form BrowserPanel
     */
    public BrowserPanel() {
        initComponents();
        WebBrowser browser;
        browser = new WebBrowser(true);
        add(browser);
    }
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(new Dimension(1000, 800));
        BrowserPanel detailPanel = new BrowserPanel();
//            cell.setBackground(new Color(34, 34, 34));
//        frame.setBackground(new Color(34, 34, 34));
        frame.add(detailPanel);
        frame.setVisible(true);
        Scanner sk = new Scanner(System.in);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
